# NOTE: not to be imported in production projects

# Separate settings will be used for local and docker containerized environments
application:
  port: 9001

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  # Setting only the development value for the `authorization_token` of EmailClient
  # For production's authorization_token, the value will be outside from version control
  authorization_token: "my-secret-token"