application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
database:
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  sender_name: "Test User"
  # Setting only the development value for the `authorization_token` of EmailClient
  # For production's authorization_token, the value will be outside from version control
  authorization_token: "Bearer my-secret-token"
  timeout_milliseconds: 10000